[project]
name = "cg"
version = "0.1.0"
description = "Avito DS bootcamp test task: candidate generation for service search (Recall@50)"
requires-python = ">=3.12,<3.13"
dependencies = [
    "pandas>=2.2",
    "pyarrow>=17",
    "numpy>=1.26,<3",
    "scipy>=1.13",
    "scikit-learn>=1.5",
    "bm25s>=0.2",
    "PyStemmer>=2.2",
    "sentence-transformers>=3.0",
    "torch>=2.3",
    "tqdm>=4.66",
    "jupyter>=1.0",
    "ipykernel>=6.29",
    "datasets>=5.0.1",
    "accelerate>=1.15.0",
    "lightgbm>=4.7.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/cg"]
