import pandas as pd, numpy as np, time
from cg.data import load
from cg.text import norm, stem_text
t=time.time()
tr = load("train"); bq = load("benchmark_queries"); bi = load("benchmark_items")
print("load", round(time.time()-t,1), tr.shape, bq.shape, bi.shape)
print("\n== dtypes train ==\n", tr.dtypes.to_string())
print("\n== dtypes bq ==\n", bq.dtypes.to_string())
print("\n== NaN share train ==\n", tr.isna().mean().round(4).to_string())
print("\n== NaN share bi ==\n", bi.isna().mean().round(4).to_string())
print("\n== id formats ==")
print("item_id len", tr.item_id.str.len().value_counts().to_dict(), bi.item_id.str.len().value_counts().to_dict())
print("query_id len", bq.query_id.str.len().value_counts().to_dict(), "unique", bq.query_id.is_unique)
print("item_id hex lower", bi.item_id.str.fullmatch(r"[0-9a-f]{16}").mean(), "bi unique", bi.item_id.is_unique)
print("\n== overlap items ==")
tr_items = set(tr.item_id); bi_items = set(bi.item_id)
print("uniq train items", len(tr_items), "corpus", len(bi_items), "corpus∩train", len(bi_items & tr_items), "share corpus in train", round(len(bi_items & tr_items)/len(bi_items),3))
print("share of train rows whose item in corpus", round(tr.item_id.isin(bi_items).mean(),3))
print("\n== overlap queries ==")
tr["q"] = tr.search_query.map(norm); bq["q"] = bq.search_query.map(norm)
trq = set(tr.q)
print("bench q exact-text in train", round(bq.search_query.isin(set(tr.search_query)).mean(),3), "norm", round(bq.q.isin(trq).mean(),3))
tr["qs"] = tr.q.map(stem_text); bq["qs"] = bq.q.map(stem_text)
print("bench qs in train", round(bq.qs.isin(set(tr.qs)).mean(),3))
print("uniq train q", tr.q.nunique(), "uniq bench q", bq.q.nunique(), "bench q dup share", round(1-bq.q.nunique()/len(bq),3))
print("\n== categories ==")
print("search_category sample", tr.search_category.head(3).tolist(), "nunique", tr.search_category.nunique(), "item_category nunique", tr.item_category_id.nunique(), "bi item_category nunique", bi.item_category_id.nunique())
print("P(item_cat==search_cat)", round((tr.item_category_id==tr.search_category).mean(),4))
print("train search_category top", tr.search_category.value_counts().head(5).to_dict())
print("bi item_category top", bi.item_category_id.value_counts().head(8).to_dict())
print("bq search_category top", bq.search_category.value_counts().head(5).to_dict())
print("microcat nunique train", tr.item_microcat_id.nunique(), "bi", bi.item_microcat_id.nunique())
print("\n== locations ==")
print("P(item_loc==search_loc)", round((tr.item_location_id==tr.search_location_id).mean(),4))
print("by delivery", tr.groupby("search_is_delivery_search").apply(lambda d: round((d.item_location_id==d.search_location_id).mean(),4)).to_dict(), tr.search_is_delivery_search.value_counts().to_dict())
print("nunique search_loc", tr.search_location_id.nunique(), "item_loc", tr.item_location_id.nunique(), "bi item_loc", bi.item_location_id.nunique(), "bq search_loc", bq.search_location_id.nunique())
print("bq loc in bi locs", round(bq.search_location_id.isin(set(bi.item_location_id.dropna())).mean(),3))
print("\n== group sizes ==")
key = ["q","search_location_id","search_category","search_infm_params_text","search_is_delivery_search"]
g = tr.groupby(key, dropna=False).item_id.agg(["size","nunique"])
print("groups", len(g), "size quantiles", g["size"].quantile([.5,.9,.99]).to_dict(), "nunique quantiles", g["nunique"].quantile([.5,.9,.99]).to_dict())
print("share rows in groups with nunique==1", round((g["nunique"]==1).sum()/len(g),3))
gq = tr.groupby("q").item_id.nunique()
print("items per q text quantiles", gq.quantile([.5,.9,.99]).to_dict())
print("microcats per q text quantiles", tr.groupby("q").item_microcat_id.nunique().quantile([.5,.9,.99]).to_dict())
print("\n== params ==")
print("train params empty share", round((tr.search_infm_params_text=="").mean(),3), "bq", round((bq.search_infm_params_text=="").mean(),3))
print(tr.search_infm_params_text.value_counts().head(8).to_string())
print("\n== texts ==")
for c in ["search_query","item_title_raw","item_description_raw","item_infm_params_text"]:
    s = (tr[c] if c in tr else bi[c]).str.len()
    print(c, "len quantiles", s.quantile([.5,.9,.99]).to_dict(), "empty", round((s==0).mean(),4))
print("bi item_infm_params sample:", bi.item_infm_params_text.head(3).tolist())
print("bi title sample:", bi.item_title_raw.head(3).tolist())
print("bq sample:\n", bq.head(5).to_string())
print("\n== item pop ==")
vc = tr.item_id.value_counts()
print("clicks per train item quantiles", vc.quantile([.5,.9,.99]).to_dict(), "max", vc.max())
print("share of bench corpus items with >=1 train click", round(bi.item_id.isin(vc.index).mean(),3))
print("total", round(time.time()-t,1))
